import { AlertCircle, Banknote, Boxes, PackageCheck, Star } from "lucide-react";


const money = new Intl.NumberFormat("en-BD", { style: "currency", currency: "BDT" });

const Overview = ({ data, loading, error, retry }) => {
  if (loading) return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map((value) => <div key={value} className="h-32 animate-pulse rounded-2xl bg-slate-200" />)}</div>;
  if (error) return <div className="empty-state"><AlertCircle className="h-12 w-12 text-rose-500" /><h2 className="mt-4 text-xl font-bold">Dashboard unavailable</h2><p className="mt-2 text-slate-600">{error}</p><button className="btn-primary mt-5" onClick={retry}>Try again</button></div>;
  const cards = [["Revenue", money.format(data.total_earnings), Banknote], ["Products sold", data.products_sold, PackageCheck], ["Active products", data.product_count, Boxes], ["Average rating", Number(data.average_rating).toFixed(1), Star]];
  return <div className="space-y-6"><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, Icon]) => <article key={label} className="surface p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><Icon size={20} /></span><strong className="mt-5 block text-2xl">{value}</strong><span className="mt-1 block text-sm text-slate-500">{label}</span></article>)}</section><div className="grid gap-6 lg:grid-cols-2"><section className="surface p-6"><h2 className="text-lg font-bold">Recent orders</h2><div className="mt-4 space-y-3">{data.recent_orders.length ? data.recent_orders.map((order) => <div key={order.item_id} className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{order.product_name}</p><p className="text-xs text-slate-500">Order #{order.id} · Qty {order.quantity}</p></div><span className="status-pill capitalize">{order.status}</span></div>) : <p className="py-8 text-center text-sm text-slate-500">No paid orders yet.</p>}</div></section><section className="surface p-6"><h2 className="text-lg font-bold">Recent reviews</h2><div className="mt-4 space-y-3">{data.recent_reviews.length ? data.recent_reviews.map((review, index) => <div key={`${review.product}-${index}`} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-3"><p className="text-sm font-bold">{review.product}</p><span className="flex items-center gap-1 text-sm font-bold"><Star size={14} className="fill-amber-400 text-amber-400" />{review.rating}</span></div><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{review.comment || "No written comment."}</p></div>) : <p className="py-8 text-center text-sm text-slate-500">No reviews yet.</p>}</div></section></div></div>;
};

export default Overview;
